# SonarQube Project Configuration
sonar.projectKey=Fraud-Detection-MLOps
sonar.projectName=Fraud-Detection-MLOps
sonar.projectVersion=1.0

# Path to the source code folders
sonar.sources=backend,frontend
sonar.exclusions=**/tests/**,**/node_modules/**,**/migrations/**

# Python test results and coverage paths
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.xunit.reportPath=backend/test-results.xml

# Language specific settings - explicitly separate JS and TS to avoid conflicts
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

# Encoding of the source code
sonar.sourceEncoding=UTF-8
