"""Add inference_logs table

Revision ID: d88a8ed8de51
Revises: b3a4f6d89a12
Create Date: 2026-03-06 07:11:34.634504+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88a8ed8de51'
down_revision: Union[str, None] = 'b3a4f6d89a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
