"""Add alerts table

Revision ID: 589200d4f988
Revises: 20260213_001
Create Date: 2026-02-25 07:39:34.122609+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '589200d4f988'
down_revision: Union[str, None] = '20260213_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hyperparameter_presets_algorithm_id'), table_name='hyperparameter_presets')
    op.drop_index(op.f('ix_preset_algorithm_name'), table_name='hyperparameter_presets')
    op.drop_table('hyperparameter_presets')
    op.add_column('alerts', sa.Column('resolution_notes', sa.String(), nullable=True))
    op.drop_column('alerts', 'resolved_notes')
    op.alter_column('classification_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('training_jobs', 'tuning_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_jobs', 'tuning_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('classification_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('alerts', sa.Column('resolved_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'resolution_notes')
    op.create_table('hyperparameter_presets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('algorithm_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('preset_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hyperparameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hyperparameter_presets_pkey'))
    )
    op.create_index(op.f('ix_preset_algorithm_name'), 'hyperparameter_presets', ['algorithm_id', 'preset_name'], unique=False)
    op.create_index(op.f('ix_hyperparameter_presets_algorithm_id'), 'hyperparameter_presets', ['algorithm_id'], unique=False)
    # ### end Alembic commands ###
