"""alert schema update

Revision ID: 3c17b76603d0
Revises: 589200d4f988
Create Date: 2026-03-03 07:24:58.867634+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c17b76603d0'
down_revision: Union[str, None] = '589200d4f988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resolved_notes', sa.String(), nullable=True))
    op.drop_column('alerts', 'resolution_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resolution_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'resolved_notes')
    # ### end Alembic commands ###
