apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
type: Opaque
stringData:
  # The GitHub Actions pipeline will replace these placeholders or they will be deployed securely via SOPS/External Secrets
  SECRET_KEY: "super-secret-local-dev-key"
  DATABASE_URL: "postgresql+asyncpg://neondb_owner:npg_md6hwLk1CotW@ep-late-forest-a1tp03d4-pooler.ap-southeast-1.aws.neon.tech/neondb?ssl=require"
  REDIS_URL: "redis://redis-master.mlops-prod.svc.cluster.local:6379"
  AZURE_STORAGE_CONNECTION_STRING: ""
  AZURE_B2C_TENANT_NAME: ""
  AZURE_B2C_CLIENT_ID: ""
