apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- namespace.yaml
- ../../base
images:
- name: shadowhubble-api
  newName: ghcr.io/mayur0522/shadowhubble-api
  newTag: main-14b50c018423c8b403c6f288c3fbb7bafc94edda
- name: shadowhubble-ui
  newName: ghcr.io/mayur0522/shadowhubble-ui
  newTag: main-14b50c018423c8b403c6f288c3fbb7bafc94edda
