apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlops-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv
  target:
    name: mlops-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE-URL
    - secretKey: REDIS_URL
      remoteRef:
        key: REDIS-URL
    - secretKey: AZURE_STORAGE_CONNECTION_STRING
      remoteRef:
        key: STORAGE-CONNECTION-STRING
    - secretKey: AZURE_B2C_TENANT_NAME
      remoteRef:
        key: B2C-TENANT-NAME
    - secretKey: AZURE_B2C_CLIENT_ID
      remoteRef:
        key: B2C-CLIENT-ID
