apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      authType: ManagedIdentity # Using VM's Managed Identity for security
      vaultUrl: "https://shadowhubble-test-v2-kv.vault.azure.net/"
